### ISSUE TITLE
Support spellcheck

### ISSUE THREAD

**Issue by voraciousdev** [writewithocto/octo#57]
Some systems have spellcheck built in, but it doesn't seem to work for octo. This might be due to the default CodeMirror configurations.

**Comment by austenmadden** [comment]
@voraciousdev I looked into this since I've been bitten by this before too. CodeMirror itself does support a spellcheck setting but I found it pretty difficult to confirm if all they added is a a hook for other modes to build on or if it's supposed to work out of the box. I can confirm it definitely does not work with `gfm` as is or at least if it would work, I was having issues getting the underlying dependencies to pick it up (vue-codemirror, etc.).

There's a lot of example community solutions for grafting on spellcheck so that's an option to. Just might be more work/uglier than is probably desirable.

If someone else wants to try it so far I've tried modifying the defaults on the codemirror window object and modifying the options passed into the vue-codemirror component (`TheEditor.vue`).

**Comment by voraciousdev** [comment]
This seems like something we will want to support even if CodeMirror doesn't have a clean implementation. I'm already extending CodeMirror functionality to autoload the language modes for code block highlighting, so I don't mind doing some "hacks" if necessary. As long as the code is isolated, I'm okay with a little bit of ugliness for now.

**Comment by voraciousdev** [comment]
Potential resource: https://github.com/sparksuite/codemirror-spell-checker

**Comment by voraciousdev** [comment]
This works out of the box with the new [Ink](https://github.com/writewithocto/ink) editor.
